#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : AbiPy Book  # The title of the book. Will be placed in the left navbar.
author                      : M. Giantomassi and the AbiPy group  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo
# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
# Auto-exclude files not in the toc
only_build_toc_files: true
  
#######################################################################################
# Execution settings

# Force re-execution of notebooks on each build. See https://jupyterbook.org/content/execute.html
execute:
  #execute_notebooks: cache
  execute_notebooks: auto
  #execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - abiref.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/abinit/abipy_book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master      # Which branch of the repository should be used when creating links (optional)


#######################################################################################
# HTML-specific settings

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_repository_button: true
  use_edit_page_button: true
  use_issues_button: true

#######################################################################################
# Parse and render settings

parse:
  myst_substitutions: 
      # Usage in md file: {{ key }}
      #
      AbinitInput: ":class:`abipy.abio.inputs.AbinitInput`"
      # 
      # Links to doc pages (AbiPy scripts)
      abistruct: "[abistruct.py](http://abinit.github.io/abipy/scripts/abistruct.html)"
      abiopen: "[abiopen.py](http://abinit.github.io/abipy/scripts/abiopen.html)"
      abicomp: "[abicomp.py](http://abinit.github.io/abipy/scripts/abicomp.html)"
      abiview: "[abiview.py](http://abinit.github.io/abipy/scripts/abiview.html)"
      abiruny: "[abirun.py](http://abinit.github.io/abipy/scripts/abirun.html)"
      abidoc: "[abidoc.py](http://abinit.github.io/abipy/scripts/abidoc.html)"
      # Links to websites
      abiconfig: "[abiconfig](https://github.com/abinit/abiconfig)"
      abiflows: "[abiflows](https://github.com/abinit/abiflows)"
      abitutorials: "[abitutorials](https://github.com/abinit/abitutorials)"
      abipygui: "[AbiPy GUI](https://panel.many2.abinit.org/)"
      #abinit-channel: https://anaconda.org/abinit
      pseudodojo: "[pseudo-dojo](http://www.pseudo-dojo.org/)"
      pymatgen: "[pymatgen](http://www.pymatgen.org)"
      #fireworks: https://materialsproject.github.io/fireworks/
      materials_project: "[materials project](https://materialsproject.org/)"
      panel: "[panel](https://panel.holoviz.org/)"
      #conda: https://conda.io/docs/
      #Anaconda: https://continuum.io/downloads
      #spack: https://github.com/LLNL/spack
      #pip: https://pypi.python.org/pypi/pip
      ipython: "[ipython](https://ipython.org/index.html)"
      jupyter: "[jupyter](http://jupyter.org/)"
      Python: "[Python](http://www.python.org/)"
      #spglib: https://atztogo.github.io/spglib/
      #bader: http://theory.cm.utexas.edu/henkelman/code/bader/
      ase: "[ase](https://wiki.fysik.dtu.dk/ase/)"
      COD: "[COD](http://www.crystallography.net/cod/)"
      CIF: "[CIF](http://www.iucr.org/resources/cif)"
      vesta: "[vesta](http://jp-minerals.org/vesta/en/)"
      xcrysden: "[XCrysDen](http://www.xcrysden.org/)"
      xmgrace: "[xmgrace](http://plasma-gate.weizmann.ac.il/Grace/)"
      gnuplot: "[gnuplot](http://www.gnuplot.info/)"
      ovito: "[ovito](https://ovito.org/)"
      v_sim: "[v_sim](http://inac.cea.fr/L_Sim/V_Sim/)"
      avogadro: "[avogadro](https://avogadro.cc/)"
      phononwebsite: "[phononwebsite](http://henriquemiranda.github.io/phononwebsite/)"
      phonopy: "[phonopy](https://atztogo.github.io/phonopy/)"
      pyprocar: "[pyprocar](https://romerogroup.github.io/pyprocar/)"
      fermisurfer: "[fermisurfer](http://fermisurfer.osdn.jp/)"
      #netcdf: https://www.unidata.ucar.edu/software/netcdf/docs/faq.html#whatisit
      YAML: "[Yaml](https://en.wikipedia.org/wiki/YAML)"
      JSON: "[JSON](https://en.wikipedia.org/wiki/JSON)"

  myst_enable_extensions:
    # default extensions to enable in the myst parser. 
    # See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    #- colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    #- linkify
    - replacements
    - smartquotes
    - substitution


launch_buttons:
  #notebook_interface: "jupyterlab"  # or "classic"
  notebook_interface: "classic"
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)


#######################################################################################
# Advanced and power-user settings

sphinx:
  extra_extensions:
      - sphinx.ext.intersphinx
      #- sphinx_click.ext
      #- sphinx_inline_tabs
      #- sphinxext.rediraffe

  config:
    # By default MathJax version 2 is currently used. 
    # You may want to try using version 3, which claims to improve load speeds by 60 - 80%:
    #mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js   # For plotly
      - https://cdn.plot.ly/plotly-2.2.0.min.js
    bibtex_reference_style: author_year  # or label, super, \supercite
    intersphinx_mapping:
        python: 
          - "https://docs.python.org/3.9"
          - null
        numpy:
          - 'https://docs.scipy.org/doc/numpy/' 
          - null
        scipy: 
          - "https://docs.scipy.org/doc/scipy/reference/"
          - null
        pandas: 
          - "http://pandas-docs.github.io/pandas-docs-travis/"
          - null
        matplotlib: 
          - "https://matplotlib.org/"
          - null
        monty: 
          - "https://pythonhosted.org/monty/"
          - null
        pymatgen: 
          - "https://pymatgen.org/"
          - null
        abipy: 
          - "https://abinit.github.io/abipy/"
          - null
    
    mathjax_config:
          # Use same Macros as the ones used in the Abinit website. See ~abinit/abinit_theme/main.html
          TeX:
           Macros:
                "*": "{\\dagger}"
                "ra": "{\\rangle}"
                "la": "{\\langle}"
                # // Workaround for bm package. See https://github.com/mathjax/MathJax/issues/1219
                bm: ["{\\boldsymbol #1}",1]
                # // Mathcal symbols
                mcL: "{\\mathcal{L}}"
                mcG: "{\\mathcal{G}}"
                mcR: "{\\mathcal{R}}"
                mcS: "{\\mathcal{S}}"
                mcC: "{\\mathcal{C}}"
                mcO: "{\\mathcal{O}}"
                # // Acronyms
                KS: "{\\text{KS}}"
                eph: "{\\text{e-ph}}"
                ee: "{\\text{e-e}}"
                phph: "{\\text{ph-ph}}"
                FM: "{\\text{FM}}"
                DW: "{\\text{DW}}"
                QP: "{\\text{QP}}"
                BZ: "{\\text{BZ}}"
                sign: "{\\text{sign}}"
                xc: "{\\text{xc}}"
                tchi: "{\\tilde\\chi}"
                # // Symbols commonly used (k-points, eigenvalues ...)
                rr: "{\\bf r}"
                RR: "{\\bf R}"
                tt: "{\\bf t}"
                GG: "{\\bf G}"
                kk: "{\\bf k}"
                qq: "{\\bf q}"
                kq: "{\\kk + \\qq}"
                qG: "{\\bf q + G}"
                kG: "{\\bf k + G}"
                kmq: "{\\kk - \\qq}"
                kpq: "{\\kk + \\qq}"
                kpG: "{\\kk + \\GG}"
                qpG: "{\\qq + \\GG}"
                nk: "{n \\kk}"
                mk: "{, \\kk}"
                nks: "{n \\kk\\sigma}"
                mks: "{m \\kk\\sigma}"
                enk: "{\\varepsilon_\\nk}"
                emkq: "{\\varepsilon_{m\\kk+\\qq}}"
                qnu: "{\\qq \\nu}"
                wqnu: "{\\omega_{\\qnu}}"
                vnk: "{\\mathbf{v}_{n\\kk}}"
                vmkq: "{\\mathbf{v}_{m\\kk+\\qq}}"
                vnka: "{\\mathrm{v}_{n\\kk,\\alpha}}"
                vnkb: "{\\mathrm{v}_{n\\kk,\\beta}}"
                ef: "{\\varepsilon_F}"
                # // EPH quantities
                gkkp: "{g_{mn\\nu}(\\kk,\\qq)}"
                gkq: "{g_{mn\\nu}(\\kk,\\qq)}"
                # //\newcommand{\gkkpL}{g_{mn\nu}^\Lc(\kb,\qb)}
                # // Many-body theory
                Go: "{G_0}"
                Wo: "{W_0}"
                Ueff: "{U_{\\text{eff}}}"
                # // Greek symbols + tilde version
                ee: "{\\epsilon}"
                tee: "{\\tilde{\\epsilon}}"
                ww: "{\\omega}"
                tww: "{\\tilde\\omega}"
                dd: "{\\,\\text{d}}"
                vxc: "{v_\\xc}"
                # // symrel
                Ri: "{\\mcR^{-1}}"
                Rit: "{\\mcR^{-1\\tau}}"
                # // symrec
                Si: "{\\mcS^{-1}}}"
                Sit: "{\\Si^\\tau}}"
                # // partial and functional derivative.
                PDER: ["{\\dfrac{\\partial #1}{\\partial #2}}", 2]
                FDER: ["{\\dfrac{\\delta #1}{\\delta #2}}", 2]
                # // PAW
                tPsi: "{\\tilde\\Psi}"
                tpsi: "{\\tilde\\psi}"
                tPhi: "{\\tilde\\Phi}"
                tphi: "{\\tilde\\phi}"
                tprj: "{\\tilde p}"
